# Generated by Django 4.2.2 on 2023-06-06 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePerson', models.CharField(max_length=60)),
                ('age', models.PositiveIntegerField(default=0)),
                ('phone', models.PositiveIntegerField(default=0, max_length=11)),
                ('city', models.CharField(max_length=40)),
                ('neighborhood', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePets', models.CharField(max_length=30)),
                ('petType', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('observation', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.person')),
            ],
        ),
    ]
